from __future__ import annotations

from typing import Protocol

from agentcanvas.domain.chat.entities import ChatMessage, Conversation
from agentcanvas.domain.dataset.entities import Dataset, DatasetVersion, StoredFile
from agentcanvas.domain.visual.dashboard import Dashboard, Visual


class UnitOfWorkPort(Protocol):
    """Frontera transaccional.

    Los casos de uso deciden cuando una operacion es atomica; el adaptador
    decide como. Sin esto, cada repositorio haria commit por su cuenta y una
    ingesta a medias dejaria un dataset sin version.
    """

    async def commit(self) -> None: ...

    async def rollback(self) -> None: ...


class StoredFileRepositoryPort(Protocol):
    async def add(self, file: StoredFile) -> None: ...

    async def get(self, file_id: str) -> StoredFile | None: ...

    async def find_by_checksum(self, owner_id: str, checksum: str) -> StoredFile | None: ...


class DatasetRepositoryPort(Protocol):
    async def add(self, dataset: Dataset) -> None: ...

    async def update(self, dataset: Dataset) -> None: ...

    async def get(self, dataset_id: str) -> Dataset | None: ...

    async def list_for_owner(self, owner_id: str) -> list[Dataset]: ...

    async def find_compatible(self, owner_id: str, fingerprint: str) -> list[Dataset]:
        """Datasets del usuario cuyo schema coincide con esa huella.

        Es lo que permite ofrecer "este archivo encaja en el dataset Ventas,
        actualizo el dashboard?" en vez de crear un dataset huerfano cada mes.
        """
        ...

    async def add_version(self, version: DatasetVersion) -> None: ...

    async def get_version(self, version_id: str) -> DatasetVersion | None: ...

    async def list_versions(self, dataset_id: str) -> list[DatasetVersion]: ...


class ConversationRepositoryPort(Protocol):
    async def add(self, conversation: Conversation) -> None: ...

    async def get(self, conversation_id: str) -> Conversation | None: ...

    async def list_for_owner(self, owner_id: str) -> list[Conversation]: ...

    async def update(self, conversation: Conversation) -> None: ...

    async def delete(self, conversation_id: str) -> None: ...

    async def add_message(self, message: ChatMessage) -> None: ...

    async def list_messages(self, conversation_id: str) -> list[ChatMessage]: ...


class DashboardRepositoryPort(Protocol):
    async def add(self, dashboard: Dashboard) -> None: ...

    async def get(self, dashboard_id: str) -> Dashboard | None: ...

    async def list_for_owner(self, owner_id: str) -> list[Dashboard]: ...

    async def rename(self, dashboard_id: str, name: str) -> None: ...

    async def delete(self, dashboard_id: str) -> None: ...

    async def add_visual(self, visual: Visual) -> None: ...

    async def get_visual(self, visual_id: str) -> Visual | None: ...

    async def list_visuals(self, dashboard_id: str) -> list[Visual]: ...

    async def update_visual(self, visual: Visual) -> None: ...

    async def delete_visual(self, visual_id: str) -> None: ...
