"""dashboards y visuales

Revision ID: 762fca0c111e
Revises: ec1b20df6d18
Create Date: 2026-08-15 12:30:28.439146
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '762fca0c111e'
down_revision: str | None = 'ec1b20df6d18'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboards',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dashboards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboards_owner_id'), ['owner_id'], unique=False)

    op.create_table('visuals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('dashboard_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=False),
    sa.Column('spec', sa.JSON(), nullable=False),
    sa.Column('placement', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visuals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visuals_dashboard_id'), ['dashboard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visuals_dataset_id'), ['dataset_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visuals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visuals_dataset_id'))
        batch_op.drop_index(batch_op.f('ix_visuals_dashboard_id'))

    op.drop_table('visuals')
    with op.batch_alter_table('dashboards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboards_owner_id'))

    op.drop_table('dashboards')
    # ### end Alembic commands ###
